spring:
  application:
    name: Gabbi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gabbi?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: gabbiAdmin
    password: gabbi
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
      enabled: true

  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 80



goodsImgLocation: src/main/resources/static/gabbi/images
uploadPath: file:src/main/resources/static/gabbi/images/
file:
  upload-dir: src/main/resources/static/videos
videoUploadPath: file:src/main/resources/static/videos/

naver:
  client-id: hIn6AfYfT3lXQQk3tdGO
  client-secret: ACIDHrghqt